inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/HashAlignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*/catalog_controller.rb'
    - 'config/**/*'
    - 'spec/**/*'
    - lib/tasks/tenejo.rake

Metrics/ClassLength:
  Exclude:
    - 'app/uploaders/csv_manifest_validator.rb'
    - 'app/controllers/catalog_controller.rb'

Metrics/MethodLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Rails/Delegate:
  Exclude:
    - 'app/models/csv_import.rb'

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/features**/*'
    - 'spec/system/**/*'
    - 'spec/uploaders/csv_manifest_validator_spec.rb'
    - 'spec/importers/modular_importer_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/EmptyMethod:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
