inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*/catalog_controller.rb'
    - 'config/**/*'
    - 'spec/features**/*'
    - lib/tasks/tenejo.rake
    - 'spec/controllers/csv_imports_controller_spec.rb'
    - 'spec/uploaders/csv_manifest_validator_spec.rb'
    - 'spec/uploaders/csv_manifest_uploader_spec.rb'
    - spec/importers/modular_importer_spec.rb
    - spec/rails_helper.rb

RSpec/AnyInstance:
  Enabled: false

Rails/Delegate:
  Exclude:
    - 'app/models/csv_import.rb'

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - 'spec/features**/*'
    - 'spec/system/**/*'
    - 'spec/uploaders/csv_manifest_validator_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/controllers/csv_imports_controller_spec.rb'

Style/EmptyMethod:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
