language: ruby
sudo: false
cache: bundler
dist: trusty
jdk:
- oraclejdk8
rvm:
- 2.5
before_script:
- bundle exec rake db:create
script:
- bundle exec rake
services:
- redis-server
- postgresql
after_success:
  - |
    if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
      openssl aes-256-cbc -K $encrypted_57e6d9c2b1f5_key -iv $encrypted_57e6d9c2b1f5_iv -in tenejo-cd.enc -out tenejo-cd -d
      bundle exec cap cd deploy
    fi
