language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - tmp/solr_downloads
    - tmp/fedora_downloads
dist: trusty
jdk:
- oraclejdk8
rvm:
- 2.5
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - bundle exec rake db:create
script:
- bundle exec rake
services:
- redis-server
- postgresql
after_success:
  - |
    if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
      openssl aes-256-cbc -K $encrypted_57e6d9c2b1f5_key -iv $encrypted_57e6d9c2b1f5_iv -in tenejo-cd.enc -out tenejo-cd -d
      bundle exec cap cd deploy
    fi
