language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - tmp/solr_downloads
    - tmp/fedora_downloads
dist: trusty
jdk:
- oraclejdk8
rvm:
- 2.6.3
addons:
  chrome: stable
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - gem update --system
  - gem install bundler
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - export DISPLAY=:99.0
  - bundle exec rake db:create
script:
- bundle exec rake
services:
- redis-server
- postgresql
