version: "3.6"

services:
  web:
    build: .
    image: curationexperts/tenejo:latest
    depends_on:
      - db
      - fedora
      - redis
      - solr
      - fedora_test
      - solr_test
    env_file:
      - ./.env.sample
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: postgres
      FEDORA_HOST: http://fedora
      FEDORA_PORT: 8080
      FEDORA_DEV_URL: http://fedora:8080/rest
      FEDORA_BASE_PATH: /dev
      FEDORA_TEST_URL: http://fedora_test:8080/rest
      FEDORA_TEST_BASE_PATH: /test
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      SOLR_URL: http://solr:8983/solr/tenejo
      SOLR_TEST_URL: http://solr_test:8983/solr/tenejo
    ports:
      - "3000:3000"
    volumes:
      - .:/tenejo
      - data:/opt/data
      - derivatives:/opt/derivatives
      - uploads:/opt/uploads
      - log:/tenejo/log
      - tenejo_tmp:/tenejo/tmp
      - tmp:/tmp
    working_dir: /tenejo
    stdin_open: true
    tty: true
  sidekiq:
    image: curationexperts/tenejo:latest
    command: ['bundle', 'exec', 'sidekiq']
    depends_on:
      - web
      - db
      - fedora
      - redis
      - solr
      - fedora_test
      - solr_test
    env_file:
      - ./.env.sample
    environment:
      DATABASE_HOST: db
      FEDORA_HOST: http://fedora
      FEDORA_PORT: 8080
      FEDORA_DEV_URL: http://fedora:8080/rest
      FEDORA_BASE_PATH: /dev
      FEDORA_TEST_URL: http://fedora_test:8080/rest
      FEDORA_TEST_BASE_PATH: /test
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      SOLR_URL: http://solr:8983/solr/tenejo
      SOLR_TEST_URL: http://solr_test:8983/solr/tenejo
    volumes:
      - .:/tenejo
      - data:/opt/data
      - derivatives:/opt/derivatives
      - uploads:/opt/uploads
      - ./bundle:/usr/local/bundle
      - log:/tenejo/log
      - tenejo_tmp:/tenejo/tmp
      - tmp:/tmp
    working_dir: /tenejo
  fedora:
    image: nulib/fcrepo4:4.7.5
    ports:
      - "8984:8080"
    volumes:
      - fcrepo_data:/data
    environment:
      JAVA_OPTIONS: "-Xmx512m"
    stdin_open: true
    tty: true
  fedora_test:
    image: nulib/fcrepo4:4.7.5
    ports:
      - "8986:8080"
    environment:
      JAVA_OPTIONS: "-Xmx512m"
  db:
    image: postgres:9
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tenejo
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:4
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  solr:
    image: solr:6.5
    volumes:
      - ./solr/config:/opt/solr/server/solr/configsets/tenejo
    ports:
      - "8983:8983"
    entrypoint:
      - solr-precreate
      - tenejo
      - /opt/solr/server/solr/configsets/tenejo
  solr_test:
    image: solr:6.5
    volumes:
      - ./solr/config:/opt/solr/server/solr/configsets/tenejo
    ports:
      - "8985:8983"
    entrypoint:
      - solr-precreate
      - tenejo
      - /opt/solr/server/solr/configsets/tenejo
volumes:
  data:
  bundle_dir:
  derivatives:
  fcrepo_data:
  log:
  pg_data:
  redis_data:
  solr_data:
  tmp:
  tenejo_tmp:
  uploads:
