version: "3.6"

services:
  web:
    build: .
    image: curationexperts/tenejo:${TENEJO_VERSION:-latest}
    depends_on:
      - db
      - fedora
      - redis
      - solr
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: tenejo
      DATABASE_PASSWORD: postgres
      FEDORA_PORT: 8080
      FEDORA_TEST_URL: http://fedora:8080/rest
      FEDORA_DEV_URL: http://fedora:8080/rest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      SOLR_URL: http://solr:8983/solr/hydra-development
      SOLR_TEST_URL: http://solr:8983/solr/hydra-test
    ports:
      - "3000:3000"
    volumes:
      - .:/tenejo
      - data:/opt/data
      - derivatives:/opt/derivatives
      - uploads:/opt/uploads
      - log:/tenejo/log
      - tenejo_tmp:/tenejo/tmp
      - tmp:/tmp
      - clam:/var/lib/clamav
    working_dir: /tenejo
    stdin_open: true
    tty: true
  fedora:
    image: nulib/fcrepo4:4.7.5-s3fix
    ports:
      - "8984:8080"
    volumes:
      - fcrepo_data:/data
    environment:
      JAVA_OPTIONS: "-Xmx512m"
    stdin_open: true
    tty: true
  db:
    image: postgres:9.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tenejo
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:4
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  solr:
    image: solr:7-alpine
    volumes:
      - ./solr/config:/opt/solr/server/solr/configsets/tenejo
    ports:
      - "8983:8983"
    command: bash -c 'precreate-core hydra-development /opt/solr/server/solr/configsets/tenejo; precreate-core hydra-test /opt/solr/server/solr/configsets/tenejo; exec solr -f'
volumes:
  data:
  bundle_dir:
  derivatives:
  fcrepo_data:
  log:
  pg_data:
  redis_data:
  solr_data:
  tmp:
  tenejo_tmp:
  uploads:
  clam:
