version: "3.6"

services:
  web:
    build: .
    image: curationexperts/tenejo:${TENEJO_VERSION:-latest}
    depends_on:
      - db
      - fedora
      - redis
      - solr
      - fedora_test
    env_file:
      - ./.env.${RAILS_ENV:-development}
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: postgres
      FEDORA_PORT: 8080
      FEDORA_DEV_URL: http://fedora:8080/rest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    volumes:
      - .:/tenejo
      - data:/opt/data
      - derivatives:/opt/derivatives
      - uploads:/opt/uploads
      - log:/tenejo/log
      - tenejo_tmp:/tenejo/tmp
      - tmp:/tmp
    working_dir: /tenejo
    stdin_open: true
    tty: true
  sidekiq:
    image: curationexperts/tenejo:${TENEJO_VERSION:-latest}
    command: ['bundle', 'exec', 'sidekiq']
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.${RAILS_ENV:-development}
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: tenejo_${RAILS_ENV:-development}
      DATABASE_PASSWORD: postgres
      FEDORA_PORT: 8080
      FEDORA_DEV_URL: http://fedora:8080/rest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/tenejo
      - data:/opt/data
      - derivatives:/opt/derivatives
      - uploads:/opt/uploads
      - log:/tenejo/log
      - tenejo_tmp:/tenejo/tmp
      - tmp:/tmp
    working_dir: /tenejo
  fedora:
    image: nulib/fcrepo4:4.7.5
    ports:
      - "8984:8080"
    volumes:
      - fcrepo_data:/data
    environment:
      JAVA_OPTIONS: "-Xmx512m"
    stdin_open: true
    tty: true
  fedora_test:
    image: nulib/fcrepo4:4.7.5
    ports:
      - "8986:8080"
    environment:
      JAVA_OPTIONS: "-Xmx512m"
  db:
    image: postgres:9.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tenejo
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:4
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  solr:
    image: solr:7-alpine
    volumes:
      - ./solr/config:/opt/solr/server/solr/configsets/tenejo
    ports:
      - "8983:8983"
    command: bash -c 'precreate-core hydra-development /opt/solr/server/solr/configsets/tenejo; precreate-core hydra-test /opt/solr/server/solr/configsets/tenejo; exec solr -f'
volumes:
  data:
  bundle_dir:
  derivatives:
  fcrepo_data:
  log:
  pg_data:
  redis_data:
  solr_data:
  tmp:
  tenejo_tmp:
  uploads:
