development:
  adapter: solr
  url: http://solr:8983/solr/tenejo
test: &test
  adapter: solr
  url: http://solr_test:8983/solr/tenejo
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/tenejo" %>
