development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fedora:8080/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://fedora_test:8080/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080/fedora/rest
  base_path: /prod
