# This is a sample config file that points to a solr server for each environment
development:
  url: http://solr:8983/solr/hydra-development
test:
  url: <%= ENV['CIRCLE_SOLR_URL'] || 'http://solr:8983/solr/hydra-test' %>
production:
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/tenejo" %>
