# This is a sample config file that points to a solr server for each environment
development:
  url: http://solr:8983/solr/tenejo
test:
  url: http://solr_test:8983/solr/tenejo
production:
  url: http://127.0.0.1:8983/solr/tenejo
